import express from 'express';
import cors from 'cors';
import helmet from 'helmet';
import pinoHttp from 'pino-http';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { config } from './config/index.js';
import { ensureDataLayout } from './core/fsLayout.js';
import { logger } from './core/logger.js';
import { ensureCollection } from './services/qdrantStore.js';
import { router } from './api/routes.js';

ensureDataLayout();
await ensureCollection();
const app = express();
app.use(helmet({ contentSecurityPolicy: false }));
app.use(cors());
app.use(express.json({ limit: '2mb' }));
app.use(pinoHttp({ logger }));
app.use('/api', router);
const here = path.dirname(fileURLToPath(import.meta.url));
app.use(express.static(path.join(here, 'web/public')));
app.use((err, req, res, next) => { req.log.error(err); res.status(500).json({ error: err.message }); });
app.listen(config.server.port, config.server.host, () => logger.info(`Maia RAG listening at http://${config.server.host}:${config.server.port}`));
